import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import usePokemonDetailData from '@/components/PokemonInfo/hooks/usePokemonDetailData';
import { pokemonKeys } from '@/const/queries';
import FetchPokemon from '@/services/FetchPokemon';
import commonServerSiderProps from '@/utils/commonServerSiderProps';

const PokemonDetail = () => {
  const { data } = usePokemonDetailData();
  return (
    <>
      <Head>
        <title>포켓몬 도감 - {data?.responseData.name || ''} 의 정보</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{data?.responseData.name || ''}</h1>
        <Image
          src={data?.responseData.sprites.front_default || ''}
          width={96}
          height={96}
          alt={data?.responseData.name || ''}
        />
      </main>
    </>
  );
};

export const getServerSideProps = commonServerSiderProps([
  {
    key: [pokemonKeys.detail],
    callback: (context: GetServerSidePropsContext) => {
      const { id } = context.query;
      return FetchPokemon.pokemon({
        pathParam: Array.isArray(id) ? id.join('') : id,
      });
    },
    fetchMode: 'NORMAL',
  },
]);

export default PokemonDetail;
