import { Inter } from 'next/font/google';
import Head from 'next/head';
import Pokemons from '@/components/Pokemons';
import { pokemonKeys } from '@/const/queries';
import FetchPokemon from '@/services/FetchPokemon';
import commonServerSiderProps from '@/utils/commonServerSiderProps';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Pokemons>
          <Pokemons.Pages />
        </Pokemons>
      </main>
    </>
  );
}

export const getServerSideProps = commonServerSiderProps([
  {
    key: [pokemonKeys.list],
    callback: FetchPokemon.pokemons,
    fetchMode: 'INFINITE',
  },
]);
